---
title: "BellaBeat Case Study"
author: "Zer En Peng"
date: '2022-05-31'
output: html_document
---

Step 1: installing and loading packages and libraries

```{r}
install.packages("tidyverse")

library(tidyverse)
library(lubridate)
library(dplyr)
library(ggplot2) #visualize data
library(tidyr) #clean data
```

Step 2: prepare the data

```{r}
dailyActivity_merged <- read.csv("C:/Users/pengz/Downloads/archive/Fitabase Data 4.12.16-5.12.16/dailyActivity_merged.csv")
dailyCalories_merged <- read.csv("C:/Users/pengz/Downloads/archive/Fitabase Data 4.12.16-5.12.16/dailyCalories_merged.csv")
dailyIntensities_merged <- read.csv("C:/Users/pengz/Downloads/archive/Fitabase Data 4.12.16-5.12.16/dailyIntensities_merged.csv")
sleepDay_merged <- read.csv("C:/Users/pengz/Downloads/archive/Fitabase Data 4.12.16-5.12.16/sleepDay_merged.csv")
weightLogInfo_merged <- read.csv("C:/Users/pengz/Downloads/archive/Fitabase Data 4.12.16-5.12.16/weightLogInfo_merged.csv")

#renaming the data to simpler terms activity
calories <- dailyCalories_merged
intensity <- dailyIntensities_merged
sleep <- sleepDay_merged
weight <- weightLogInfo_merged
activity <- dailyActivity_merged

#remove duplicates
activity <- activity[!duplicated(activity),]

#checking duplicated rows after cleaning
sum(duplicated(activity))
sum(duplicated(intensity))

#check missing value from each column 
sum(is.na(weight)) 

#display missing values 
is.na((weight)) 

#exclude weight column 
weight %>% filter(!is.na(Fat)) 

#removing "Fat" column from the analysis 
weight2 <- subset(weight,select = -Fat) 

#checking 
sum(is.na(weight2))

#Seperate data and time to two columns 
sleep <-sleep %>% + separate(SleepDay,c("date","time")," ") 
weight<-weight %>% separate(Date,c("date","time")," ") 
activity$date <- as.Date(activity$ActivityDate, format="%m/%d/%y") 
calories$ActivityDay <- as.Date.character(calories$ActivityDay, format = "%m/%d/%y") 
intensity$time <- as.Date(intensity$ActivityDay, format ="%m/%d/%y") 
sleep$date <- as.Date.character(sleep$date, format = "%m/%d/%y") 
weight$date <- as.Date.character(weight$date, format = "%m/%d/%y")

#merging data 
sleep_activity <- merge(sleep, activity,by=c("Id", "date")) head(sleep_activity)
```

Step 3: Examine the dataset

```{r}
#exploring and summarizing data 
n_distinct(activity$Id) 
n_distinct(calories$Id) 
n_distinct(intensities$Id) 
n_distinct(sleep$Id) 
n_distinct(weight2$Id) 
nrow(activity) 
nrow(sleep)

head(activity) 
summary(activity) 
str(activity) 
summary(calories) 
summary(sleep) 
summary(weight)
```

Step 4: Visualization

```{r}
#visualization 

ggplot(data=activity, aes(x=TotalSteps, y=Calories)) + geom_point() + geom_smooth() + labs(title="Total Steps vs. Calories")

ggplot(data=sleep, aes(x=TotalMinutesAsleep, y=TotalTimeInBed)) + geom_point()+ labs(title="Total Minutes Asleep vs. Total Time in Bed")

##Comparing Weekday vs Weekend Activity 

activity$weekday <- weekdays(activity$date) average_steps <- aggregate(TotalSteps ~ weekday, activity, mean) average_steps$weekday <- ordered(average_steps$weekday, levels=c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")) 

ggplot(average_steps, aes(x=weekday, y=TotalSteps)) + geom_bar(stat="identity", fill="yellow") + geom_text(aes(label=round(TotalSteps, digits = 0)), color="black", size=5.5) + labs(title = "Total Steps Walked on Average", x="Day", y="Number of Steps") + theme(plot.title = element_text(hjust = 0.5, size=20), axis.text=element_text(size=10), axis.title=element_text(size=14), axis.title.y=element_text(margin = margin(t = 0, r = 15, b = 0, l = 0)), axis.title.x=element_text(margin = margin(t = 15, r = 0, b = 0, l = 0)))

##minutes asleep vs sedentary minutes 

ggplot(data=sleep_activity, aes(x=TotalMinutesAsleep, y=SedentaryMinutes)) + geom_point(color='red') + geom_smooth() + labs(title="Minutes Asleep vs. Sedentary Minutes")
```
